# Generated by Django 4.1.3 on 2022-12-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_proyecto_id_tarea_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Primer_nombre', models.CharField(max_length=30)),
                ('Segundo_nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PersonaProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.persona',),
        ),
    ]
